backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "sajt"
    label: "Sajt"
    files:
      - file: "content/site.json"
        label: "Podešavanja sajta"
        name: "site"
        fields:
          - label: "Naslov O nama"
            name: "about_title"
            widget: "string"
          - label: "Tekst O nama"
            name: "about_text"
            widget: "text"
          - label: "Galerija"
            name: "gallery"
            widget: "list"
            fields:
              - label: "Slika"
                name: "image"
                widget: "image"
              - label: "Opis slike"
                name: "alt"
                widget: "string"
                required: false